### ISSUE TITLE
weird middle-of-round fake boss interrupt

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#1]
uncommonly, sometimes the mod bugs out and the person to be the boss has the model applied but doesn't lose their items or have any boss code running, so it looks like a normal player with a boss model on them and their class weapons.

**Comment by Starblaster64** [comment]
Pretty sure this may be a client-side TF2 bug. It's happened to me and some others I know before on VSH and FF2 alike.
