### ISSUE TITLE
Multi-boss rounds allow multiples of the same boss

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#10]
Is this a bug or a feature? It seems kind of silly though when you get a triple-boss round with all Saxton Hales.

**Comment by assyrianic** [comment]
that's a feature. Purpose is that you can have any boss of any limit.
The thing with multibosses is that the developer should control the amounts of multibosses and how many.

For example, on a 32 man server, if a developer wishes then he or she can actually make a 30-player boss round against 2 reds.

**Comment by Starblaster64** [comment]
So you control how many of one boss can spawn in one round in the Boss.sp or where?

**Comment by assyrianic** [comment]
you can only, at the moment, control it in the boss handler function `public void ManageOnBossSelected(const BaseBoss base);`

**Comment by assyrianic** [comment]
I think there should be a wiki on how to do custom bosses and other stuff etc.

**Comment by Starblaster64** [comment]
https://github.com/Starblaster64/Vs-Saxton-Hale-2/wiki
