### ISSUE TITLE
call_onmessageintro change function placement

### ISSUE THREAD

**Issue by Shinyscales** [Starblaster64/Vs-Saxton-Hale-2#110]
in ManageMessageIntro

move the Format and sethudparams above the call_onmessageintro

```
		SetHudTextParams(-1.0, 0.2, 10.0, 255, 255, 255, 255);
		Format(intro_msg, MAXMESSAGE, "%s\n%N has become %s with %i Health", intro_msg, base.index, name, base.iHealth);
		Action act = Call_OnMessageIntro(base, intro_msg);
		if( act > Plugin_Changed )
			continue;
		
```

so the call function can modify it without it being set to default

**Comment by kevyonan** [comment]
done with update [v2.5.7](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/commit/b6a9754d26a131ea0ab0b25b2654310d49f2f45e)
