### ISSUE TITLE
Add HookSound api callback

### ISSUE THREAD

**Issue by Epinomis** [Starblaster64/Vs-Saxton-Hale-2#116]
I am currently porting a bunch of ff2 hales to vsh2, and many of them require having class voicelines disabled like HHH or Saxton.

The handler function HookSound vsh2 uses does not have a callback, so I would have to add a sdk AddNormalSoundHook to each hale that requires this, but it would be easier, faster and cleaner if this functionaly was also added to the vsh2 api.

**Comment by Scags** [comment]
I second this proposal. In my own port of VSH2, I've even added a native to quickly block all voice lines for a certain boss id (since blocking all voice lines is the most common). @assyrianic thoughts?

**Comment by kevyonan** [comment]
Sure, any params in mind to implement?

**Comment by kevyonan** [comment]
```c
function void (VSH2Player player, char sample[PLATFORM_MAX_PATH], int& channel, float& volume, int& level, int& pitch, int& flags);
function Action (VSH2Player player, char sample[PLATFORM_MAX_PATH], int& channel, float& volume, int& level, int& pitch, int& flags);
```

**Comment by Epinomis** [comment]
Params look fine to me. I think it could be split to an OnBossMakeSound and an OnRedMakeSound, though I currently have no use for the red part I can see it being useful if you ever want to disable/modify merc voice or even do some kind of voiceline trigger.

**Comment by kevyonan** [comment]
@Yoitsu well technically you could just check if the `player` instance is a boss or not and then check further based on that confirmation.

**Comment by Epinomis** [comment]
True, but I thought having them as seperate would be more in line with the rest of the api which is mostly seperated to different hooks for the teams (though having a single hook would probably be cleaner over all). Both ways are fine for me.

**Comment by kevyonan** [comment]
@Yoitsu alright, VSH2 v2.6.14 is up with your requested API changes.
Look at the example code in the [template boss for completely blocking all stock voicelines](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/vsh2boss_template.sp#L377-L385)

**Comment by Epinomis** [comment]
Thank you!
