### ISSUE TITLE
Cannot evaluate the square root of a negative number (val: -x)

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#12]
L 09/04/2016 - 11:59:21: [SM] Exception reported: Cannot evaluate the square root of a negative number (val:-51.000000)
L 09/04/2016 - 11:59:21: [SM] Blaming: vsh2.smx()
L 09/04/2016 - 11:59:21: [SM] Call stack trace:
L 09/04/2016 - 11:59:21: [SM]   [0] SquareRoot
L 09/04/2016 - 11:59:21: [SM]   [1] Line 656, modules/base.sp::BaseBoss.GiveRage()
L 09/04/2016 - 11:59:21: [SM]   [2] Line 734, modules/handler.sp::ManageHurtPlayer()
L 09/04/2016 - 11:59:21: [SM]   [3] Line 79, modules/events.sp::PlayerHurt()

**Comment by assyrianic** [comment]
hmmm there's many ways to fix this, I can have the GiveRage method check if the damage is zero or I can check if the damage event integer is 0. Which do you think is better?

**Comment by Starblaster64** [comment]
I'm not quite sure what's going on in Line 656. Why do you need to square root anything at all?
In response to your question though, probably putting a check in the GiveRage method, since it's supposed to be for **giving** Rage.

**Comment by assyrianic** [comment]
the reason for the square root is the rage formula which scales by health and damage.

`this.flRAGE += ( damage/SquareRoot(float(health))*4.0 );`

**Comment by Starblaster64** [comment]
I'm still confused about how that works. Is it supposed to be out of 100%? Whatever I put in my calculator, the result remains virtually the same.
105 / (2 yroot (2048) * 4) = 26.241117170526396703482667805024
105 / (2 yroot (8188) * 4) = 26.247777925822348872688021104273

**Comment by assyrianic** [comment]
yes that's intentional, more health = more opportunities to have rage.

**Comment by Starblaster64** [comment]
Ohh, I see.
The way I had it set up in my custom fork of VSH was just like a reverse Backstab formula. Hale would get a min of 1 Rage per round at lower HPs, and after each Rage the damage required for the next Rage would thereafter be affected by Hale's MaxHP and number of Rages beforehand. So the more you Raged, the more damage you'd need for the next one.

**Comment by assyrianic** [comment]
again, you can always override it via your own rage code for custom bosses. That's the power of this plugin :8ball:
