### ISSUE TITLE
Add one-off callback at the start of the round

### ISSUE THREAD

**Issue by Epinomis** [Starblaster64/Vs-Saxton-Hale-2#120]
I looked over the documentation and source code and couldn't find anything for this.

There doesn't seem to be a one-off callback for when the round starts, the transition between StateStarting and StateRunning but after OnVariablesReset, which I think is a very common use case for setting up per-round code. I'm trying to set up a custom hale challenge mode that works at the level of entire round instead of a single boss, and none of the boss hooks are really usable for this use case without hacky code since they are run for each boss instead of once.

**Comment by kevyonan** [comment]
In terms of that lull between `StateStarting` and `StateRunning`, I could suggest hooking to `arena_round_start` like `HookEvent("arena_round_start", ArenaRoundStart);`

If that doesn't meet your needs, let me know.

**Comment by Epinomis** [comment]
That's what I was thinking about, but is there a way to guarantee that my hook is always launched after vsh2's own ArenaRoundStart hook? I'm frankly new to sourcepawn/sourcemod (but not in programming in general) and my primary worry over straight up hooking on that event is that if I say, need correct information over the health of the bosses, and my hook is launched before vsh2's own which initializes them with Call_OnBossCalcHealth.

**Comment by kevyonan** [comment]
well I guess I could add a one-off hook, addons as opposed to bosses would find it more useful.
`StateStarting` is set _after_ OnBossSelected forward is fired. `StateRunning` is set as soon as the Boss Health has been announced in the center message when the round starts. So when do you need the one-off hook to fire?

**Comment by Epinomis** [comment]
I think the hook should be after all of vsh2's internal per-round start of round functions have completed (it doesn't make sense to work on an incomplete state) but before the players can move or affect the state of the round, so pretty much the same timing as ArenaRoundStart but with the guarantee that it's always executed after it.

So wouldn't adding a call at then end of ArenaRoundStart make sense?

**Comment by kevyonan** [comment]
well `OnMessageIntro` is fired at the end of `ArenaRoundStart` but I'm guessing you already saw about it and it wasn't what you needed?

**Comment by Epinomis** [comment]
From the look of it OnMessageIntro is called for each boss? The timing on it is right, though.

**Comment by kevyonan** [comment]
yes, it's called on each boss. Are you worried about performance?

**Comment by Epinomis** [comment]
I believe we've had a bit of an miscommunication. The point was for a hook that would be launched only once per round, indepedent of how many bosses there are, since the addon has nothing to deal with individual bosses.

I think OnMessageIntro could be reused for this purpose with some hacky code like setting a global boolean after the first callback that makes the rest of callbacks do nothing, but it's not a stable api because of the hook misuse which could break things if they were to change internally. If you think this use case is not common enough to warrant being added to the main repo that's fine, I can add it to my private fork.

**Comment by kevyonan** [comment]
well it depends _what_ you're trying to accomplish. You don't need to use the variables in the hook, you can simply just use the hook for anything. Is the code you plan to run that expensive to which it requires a once fired hook?

**Comment by Epinomis** [comment]
I don't require it to be fired once because it's expensive, but because it should only be fired once.

I'm trying to implement a ticket mode for vsh2, where red has a number of tickets they can use for respawns during the round, until the ticket count drop to zero. If one boss has this enabled, it's enabled for the round as a whole and the challenge-mode settings for other bosses are ignored as you can't enable the mode multiple times.

In addition to this, I plan on implementing other modes too which operate on a per-round level instead of per-boss, and only one of these can be enabled at a time, so I have to do various types of checks to find out which mode to play out (added complexity compared to ff2 due to any number of bosses being a possibility). For this I have to gather up all the bosses at once and find out the mode to play, which I need to fire only once per round, not caring about the particular bosses in question.

So yes, I could use OnMessageIntro, set a global on the first callback, and make the rest of the callbacks return early based on that global, but it simply would be hacky coding.

**Comment by kevyonan** [comment]
Perhaps I could add an `OnRoundStartInfo` callback. Not sure what parameters to give it.
Another thing is that I'm reluctant to add alot of forwards is because I want to prevent VSH2 from suffering feature creep but it seems this addition wouldn't hurt so why not?

**Comment by Epinomis** [comment]
Frankly - it wouldn't even really need anything since you can get all the information you need through the utility functions VSH2 already has. Possibly it could give the list of bosses and players, something it the lines of (const VSH2Player[] bosses, const int boss_count, const VSH2Player[] red_players, const int red_count), since you're already looping through all clients in ArenaRoundStart

**Comment by kevyonan** [comment]
sounds good.
Something like `OnVSH2RoundStart`
```c
function Action (const VSH2Player[] bosses, const int boss_count, const VSH2Player[] red_players, const int red_count);
```

**Comment by Epinomis** [comment]
Looks good to me.

**Comment by kevyonan** [comment]
alright, this has been implemented and it'll be ready in the next update

**Comment by Epinomis** [comment]
Thank you.
