### ISSUE TITLE
Add OnBossCalcHealthPost

### ISSUE THREAD

**Issue by Epinomis** [Starblaster64/Vs-Saxton-Hale-2#121]
There's currently an issue with OnBossCalcHealth - setters (i.e. max_health = 1000) and modifiers (i.e. max_health *= 0.5) use the same hook, which will sometimes make the changes by modifiers that use the supplied max_health be overridden by setters that set a completely new, seperate from the old one. Even the exampe difficulty addon suffers from this - with hook based bosses, the OnBossCalcHealth modifications by the health reduction settings are overridden by the boss's own OnBossCalcHealth setter, if the latter happens comes afterwards.

This could be solved by splitting OnBossCalcHealth to two - OnBossCalcHealth for setter(s) and OnBossCalcHealthPost for modifiers. This would make sure that anything that modifies the max health would apply properly and not be overridden.

**Comment by Epinomis** [comment]
PS. I can try submitting a pull request for this or the other issue of mine if you'd like, I wouldn't want to inconvinience you too much with constant requests.

**Comment by kevyonan** [comment]
yeesh, this sounds like a bug.

**Comment by kevyonan** [comment]
ok so this is not exactly a bug but I'm going to change its functionality so that plugin order won't overly affect this as much. I will need time to think up a solution.

**Comment by kevyonan** [comment]
This is also a work around but a valid one, another thing that can be done is modifying the property `iMaxHealth`.
The `OnBossCalcHealth` forward existed _before_ I migrated VSH2's health system to use TF2's native health system.

**Comment by kevyonan** [comment]
@Yoitsu An alternative here is to use `OnRoundStart` as if it was `OnBossCalcHealthPost`.

**Comment by Epinomis** [comment]
Yes, I think that'll solve this issue. I looked over at your implementation on the addon repo, and the new iMaxHealth stays the same if the boss happens to get respawned, correct?

**Comment by kevyonan** [comment]
it should.

**Comment by Epinomis** [comment]
Well, I think this should solve it. Thanks!
