### ISSUE TITLE
Mini-crits on airborne targets attribute non-functional

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#13]
@assyrianic You're using the now defunct attribute 265 for mini-crits on airborne targets. You'll need to switch over to how I fixed it in VSH using the 'new' attribute (114 ; 1). [Here](https://github.com/Starblaster64/Versus-Saxton-Hale/blob/pre-156/addons/sourcemod/scripting/saxtonhale.sp#L4109). You can replace TFCond:99 with TFCond_GrapplingHookSafeFall, I just never got around to doing it.

**Comment by assyrianic** [comment]
strange, items_game.txt still lists it despite not being used. Maybe it really is defunct.

also for the tf cond, wouldn't it make more sense to add it to the bosses when their ONGROUND flag is false? Seems about right, I'll add this within 1.2.1 :8ball:

**Comment by Starblaster64** [comment]
The attribute exists, but Valve decided to obliterate any functionality it had for some reason. The TFCond thing doesn't matter, since the game will check if the player being shot at is in the air automatically.

**Comment by assyrianic** [comment]
fixed :3
