### ISSUE TITLE
Remove code that relies on offsets in TF2_GetNumWearables and TF2_GetWearable

### ISSUE THREAD

**Issue by bottiger1** [Starblaster64/Vs-Saxton-Hale-2#136]
This code needs to be removed. I don't want to have to worry about vsh2 crashing every new update that comes out and then having to recompile vsh2.

Even if we have to iterate through 2048 entities, it would be preferrable to this.

```
stock int TF2_GetNumWearables(int client)
{
	/// 3552 linux
	/// 3532 windows
	int offset = FindSendPropInfo("CTFPlayer", "m_flMaxspeed") - 20 + 12;
	return GetEntData(client, offset);
}
stock int TF2_GetWearable(int client, int wearableidx)
{
	/// 3540 linux
	/// 3520 windows
	int offset = FindSendPropInfo("CTFPlayer", "m_flMaxspeed") - 20;
	Address m_hMyWearables = view_as< Address >(LoadFromAddress(GetEntityAddress(client) + view_as< Address >(offset), NumberType_Int32));
	return LoadFromAddress(m_hMyWearables + view_as< Address >(4 * wearableidx), NumberType_Int32) & 0xFFF;
}
```

**Comment by Scags** [comment]
I disagree. The probability of that offset changing is so rare, the plugin is more likely to break from some other issue altogether.

To clarify, that offset is from the CBasePlayer class in the 2013 SDK. Although the offset is 20 bytes from `m_flMaxspeed`, they're actually [1 member apart](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/player.h#L1071-L1079). The probability of a change in the sdk file that happens to be between those 2 so monumentally rare, [this](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/bosses/bunny.sp#L305) is more likely to change instead.

**Comment by bottiger1** [comment]
I don't think you can say how rare it might be. Offsets change all the time and tf2 is not obligated to be compatible with 2013 SDK. Compiler changes can add padding,  and what people think would never happen has happened. Maybe CUtlVector will change. When it comes to Econ items, anything can change.

I'm not comfortable worrying that an update being dropped in the middle of the day will kill my vsh2 server until I have the time to reverse engineer this and then having to recompile vsh2 just to fix this. If easter egg has a similar problem then it needs to be changed too.

Or if it can't be changed then it needs to be loaded from gamedata. But from what I can tell this is just premature over optimization.  If it comes down to looping through 2048 entities a few times when players spawn vs making this plugin liable to break on updates, I'd pick the tiny inefficiency over the loss of stability.

**Comment by Scags** [comment]
No plugin is future-proof. Valve's updates are absolutely unpredictable. Regardless, that behavior has been the same for 7 years. What makes you think a simple midday update will change that all of a sudden?
