### ISSUE TITLE
Merge bIsBoss and iBossType

### ISSUE THREAD

**Issue by Epinomis** [Starblaster64/Vs-Saxton-Hale-2#140]
Duplicated information, and can possibly go off-sync causing all kinds of problems. iBossType >= already implies bIsBoss so there's no need to use 2 props to track being a boss.

My suggestion for merging:
Make iBossType == 0 not being a boss and iBossType > 0 being a boss, replace bIsBoss getter/setter by a getter iBossType > 0. With iBossType == 0 being the default state it nicely matches StringMap returning 0 by default on uninitialized keys, it eliminates bugs that could happen from a player getting to play without ManageResetVariables being called first (#139)

**Comment by kevyonan** [comment]
I guess to keep backwards compatibility, I could technically have the internals use `bIsBoss` as `iBossType > -1`. Same with getting `bIsBoss` from `GetPropAny`.

**Comment by Epinomis** [comment]
That's what I also had in mind, bIsBoss could be converted to a getter only property. This will still break plugins that set bIsBoss, so the change probably should be done only when the next api breaking update comes out (3.0?)

**Comment by kevyonan** [comment]
no worries, no modules should ever modify `bIsBoss` so this is a change I'm willing to do.
