### ISSUE TITLE
shortlist of requests (forwards and adjustments)

### ISSUE THREAD

**Issue by Shinyscales** [Starblaster64/Vs-Saxton-Hale-2#144]
- message forwards like onroundstart, onroundend, etc move Format function above the forward call() so the forward may edit the message
_currently the forwards that deal with the text displayed for those events get reverted since vsh2 has **format** function right after the forward is called_

- add a message forward for the "Total Boss Health" hud
_so an addon may modify what is there for the boss health ( in my case a custom health system )_

- onhit forwards override default behaviour if forward is Plugin_Changed
_for example, if an onhitcandycane is plugin_changed, don't use default behaviour which is spawn healthkit_

- add forward for climbwall function
_maybe set a forward for red players using climbwall function?_

**Comment by kevyonan** [comment]
alright, so bullet 1 and 3 have been implemented!

**Comment by kevyonan** [comment]
added OnPlayerClimb in v2.10.28
