### ISSUE TITLE
Boss instantly losing

### ISSUE THREAD

**Issue by Rjeek** [Starblaster64/Vs-Saxton-Hale-2#145]
the boss loses instantly. The server writes that the boss is disconnected. But the boss on server. Help me please

**Comment by kevyonan** [comment]
can you be more specific? What version are you using?

**Comment by Rjeek** [comment]
Im using version 2.8.25

**Comment by Rjeek** [comment]
I can make a video about this bug If you want to see it

**Comment by kevyonan** [comment]
yes. If I can ask, do you have other plugins alongside VSH2? Can you test just with VSH2 by itself?

**Comment by Rjeek** [comment]
on VSH2 only multibosses and PlagueDoctor. I'll record a video today and show it to you

**Comment by kevyonan** [comment]
what version of sourcemod and metamod are you using?

**Comment by Rjeek** [comment]
SourceMod (1.10.0.6490), Metamod:Source 1.10.6

**Comment by Rjeek** [comment]
Im sorry if I dont give you a lot of information

**Comment by Rjeek** [comment]
https://www.youtube.com/watch?v=WIocOwjjoXw&ab_channel=WeezCruel

this bug

**Comment by Rjeek** [comment]
I fix it
