### ISSUE TITLE
individual bosses die in one-backstab during multiboss round

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#15]
pretty much the title

**Comment by Starblaster64** [comment]
Is this a constantly occurring  issue, or just a some-times-occurring issue? So far I haven't had it happen to me once.

**Comment by assyrianic** [comment]
I only experienced this a couple times but it's worth having an issue on it. I'm not sure if it's happening anymore or not but.
