### ISSUE TITLE
Question: how to implement bosses with multiple lives

### ISSUE THREAD

**Issue by Pheubel** [Starblaster64/Vs-Saxton-Hale-2#168]
I am trying to create a boss that has multiple lives. My current attempt has me setting the iLives property during `OnBossInitialized` and then using the code below during `OnBossDeath`, but the boss still dies as if it has it only has one health.

```
Action HandleOnBossDeath(const VSH2Player player) {
    int lives = player.GetPropInt("iLives") - 1;

    if(lives > 0){
        player.SetPropInt("iLives", lives);
        player.iHealth = player.GetPropInt("iMaxHealth");
        return Plugin_Handled;
    }

    return Plugin_Continue;
}

void HandleOnBossRealDeath(const VSH2Player player) {
    if( !IsBossType(player, BossId)) {
        return;
    }

    PlayRandomSoundFromConfigSelector(player, BossConfig, VSH_DEFAULT_SELECTOR_SOUNDS_DEATH, VSH2_VOICE_LOSE);
}
```

**Comment by kevyonan** [comment]
`OnBossDeath` hook fires when the boss is actually killed (e.g. the `player_death` event is fired).

As a suggestion, I say to try hooking to `OnBossTakeDamage*`, check if the damage is enough to kill the boss, then run the lives logic code.

**Comment by Pheubel** [comment]
thanks for the suggestion, i've tried the following but still no dice. i might've made a mistake but the boss seems to die before the finishing blow can fire.

(i am on version 2.10, so it might behave differently on version 2.11)

```
Action HandleOnBossTakeDamage(VSH2Player victim, int& attacker, int& inflictor, float& damage, int& damagetype, int& weapon, float damageForce[3], float damagePosition[3], int damagecustom) {
    int bossId = victim.GetPropInt("iBossType");

    if(!IS_CONFIG_BOSS(bossId)) {
        return Plugin_Continue;
    }

    LogMessage("boss Id: %i\nboss health: %i\nboss lives: %i\ndamage: %f", bossId, victim.iHealth, victim.GetPropInt("iLives"), damage);

    if((float(victim.iHealth) - damage) > 0.0) {
        return Plugin_Continue;
    }

    int lives = victim.GetPropInt("iLives") - 1;

    // check if boss lost last life
    if(lives <= 0) {
        return Plugin_Continue;
    }

    damage = 0.0;
    victim.SetPropInt("iLives", lives);
    victim.iHealth = victim.GetPropInt("iMaxHealth");

    ConfigMap bossConfig = GET_BOSS_CONFIG(bossId);

    PlayRandomSoundFromConfigSelector(victim, bossConfig, VSH_DEFAULT_SELECTOR_SOUNDS_LIFE_LOST, VSH2_VOICE_RAGE);

    Call_StartForward(onLifeLost);
    Call_PushCell(victim);
    Call_PushCell(attacker);
    Call_PushCell(bossConfig);
    Call_Finish();

    return Plugin_Handled;
}
```

when i look at the server console to see the message output it also seems to skip a consistent amount of events, since the health goes down 30 each report while the damage per report is only 10. (Now that i am lying in bed and thinking about it, maybe it went down by 30 because of crits. I'll look into it more when i wake up, if it is indeed the case that damage is without crits applied then i need to find a reliable way to check for mini/full crits)
![afbeelding](https://user-images.githubusercontent.com/22686676/118040870-66f66700-b372-11eb-952a-409e9a2df17c.png)

**Comment by Pheubel** [comment]
After looking online i found that by hooking into `SDKHook_OnTakeDamageAlive` i would get the actual damage the boss player would be receiving and the code seems to work now. i did have to hook it in a more roundabout way, since it also needed the entity when creating the hook, so i had to set it when the boss would be initialized by one of the VSH2 hooks. 

It would be nice if the actual damage were to be visible in when the boss/players get hurt, but i can get that that would be a bit more of an undertaking.

**Comment by Bertold428** [comment]
can you send me the code because I also want to give more lives to the boss, but I don't know how.
