### ISSUE TITLE
All Fall Damage Negated

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#17]
For some reason all fall damage is being negated while VSH2 is running.

**Comment by assyrianic** [comment]
```java
public Action OnTakeDamage(int victim, int& attacker, int& inflictor, float& damage, int& damagetype, int& weapon, float damageForce[3], float damagePosition[3], int damagecustom)
{
	if ( not bEnabled.BoolValue or not IsClientValid(victim) )
		return Plugin_Continue;

	BaseBoss BossVictim = BaseBoss(victim);
	int bFallDamage = (damagetype & DMG_FALL);
	if (BossVictim.bIsBoss and attacker <= 0 and bFallDamage) {
		damage = (BossVictim.iHealth > 100) ? 1.0 : 30.0;
		return Plugin_Changed;
	}
	
	if (BossVictim.bIsBoss) // in handler.sp
		return ManageOnBossTakeDamage(BossVictim, attacker, inflictor, damage, damagetype, weapon, damageForce, damagePosition, damagecustom);

	if (!IsClientValid(attacker))	// BUG PATCH: Client index 0 is invalid
		return Plugin_Continue;
	
	BaseBoss BossAttacker = BaseBoss(attacker);
	if (BossAttacker.bIsBoss) // in handler.sp
		return ManageOnBossDealDamage(BossVictim, attacker, inflictor, damage, damagetype, weapon, damageForce, damagePosition, damagecustom);

	return Plugin_Continue;
}
```

This is the current OnTakeDamage code, doesn't look like there's any negation of fall damage exception for the boss.

**Comment by assyrianic** [comment]
testing right now on my private server and it doesn't seem to block fall damage, are other people having this issue?

**Comment by Starblaster64** [comment]
I will test again this weekend, I'll try chucking in several debug messages to see if I can find the source.
Could it be another one of those OS specific bugs like the compile issue?

**Comment by assyrianic** [comment]
is this bug still going on?

**Comment by Starblaster64** [comment]
I'll test it again today, been kinda busy and forgot about it.

**Comment by Starblaster64** [comment]
While were on the topic of OnTakeDamage, should we add another event for OnTakeDamageAlive and OnTakeDamage(Alive)Post? Or would those just be extra niche features that developers should add themselves.

**Comment by Starblaster64** [comment]
Fall damage bug seems to have been fixed, unsure how it was occurring in the first place though.

**Comment by assyrianic** [comment]
OnTakeDamageAlive and Post would be niche features. I don't see what boss I can officially add in that requires those hooks.
Since the Fall dmg bug has been fixed, I'm closing this issue.
