### ISSUE TITLE
[Bug] Freak Fortress bridge broken due to stricter plugin loading

### ISSUE THREAD

**Issue by Pheubel** [Starblaster64/Vs-Saxton-Hale-2#172]
The freak fortres 2 bridge for VSH2 relies on sub plugins having the `.ff2` file extension, this has been standard for FF2 for a long time, however due to recent changes to sourcemod the loading of plugins has been restricted to `.smx` only (see: https://github.com/alliedmodders/sourcemod/pull/1437 ).

### Proposed solution:
The first step would go as followd. If the ff2 bridge is being used subplugins should be renamed to use the `.smx` extension instead. The new code would be similair to the one that can be found on the [Freak Fortress 2 main branch](https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/scripting/freak_fortress_2.sp#L1106). This would take care of the plugins having invalid extensions.

The second step would be a small change to lines like these: 
[ServerCommand("sm plugins load \"freaks\\%s.ff2\"", name);](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/ff2/subplugins.sp#L65)
[ServerCommand("sm plugins unload \"freaks\\%s.ff2\"", info.name);](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/ff2/subplugins.sp#L103)
[FormatEx(pl_name, sizeof(pl_name), "freaks\\%s.ff2", name);](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/ff2/subplugins.sp#L113)
Instead of appending ".ff2" it should append ".smx" instead, this way it will load the newly renamed ff2 subplugins.

**Comment by kevyonan** [comment]
@01Pollux
