### ISSUE TITLE
OrdMap for ConfigMap

### ISSUE THREAD

**Issue by MAGNAT2645** [Starblaster64/Vs-Saxton-Hale-2#175]
Would be good if `ConfigMap` could follow insertion order (via [`OrdMap`](https://forums.alliedmods.net/showthread.php?t=331318) or something like that).
As i remember currently there's no real order due to using `StringMap`.
With this it would be easier to iterate through config sections and keys in appropriate order.

Also, can you give an example on how to iterate sections (and keys) with current `ConfigMap` implementation (i'm not talking about integer keys)?

**Comment by kevyonan** [comment]
I don't use `OrdMap` because it'd create a hard C++ dependency for VSH2 and my policy with VSH2 is having as little dependencies as possible. Less dependencies means less things that can break from new TF2 updates which also means faster response to fixing/updating for new TF2 updates.

Did you look at the [wiki page](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/wiki/Using-ConfigMap-(Tutorial)) for using `ConfigMap`?

Example:
```
"root" {
    "kv1": "value"
    "subsection": {
        "subkey": "subvalue"
    }
}
```
```java
int value_len = cfg.GetSize("root.kv1");
char[] value_str = new char[value_len];
if( cfg.Get("root.kv1", value_str, value_len) > 0 ) {
    PrintToServer("%s", value_str);
}

ConfigMap subsection = cfg.GetSection("root.subsection");
if( subsection != null ) {
    ...;
}
```

**Comment by MAGNAT2645** [comment]
But what if i don't know what subsections are in the config? I want to iterate them. I know that i can use `StringMapSnapshot` but is there any proper way to iterate sections and keys?

**Comment by MAGNAT2645** [comment]
I remember only one example of recursive iteration: [`PrintCfg`](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/include/cfgmap.inc#L811-L839) but i thought there may be better way.

**Comment by kevyonan** [comment]
> But what if i don't know what subsections are in the config? I want to iterate them. I know that i can use `StringMapSnapshot` but is there any proper way to iterate sections and keys?

Not exactly a common situation to be in, usually config writers know subsections but `StringMapSnapshot` is the only way if you don't know what string names there are:
```java
	StringMapSnapshot snap = cfg.Snapshot();
	if( snap==null ) {
		return;
	}
	int entries = snap.Length;
	for( int i; i<entries; i++ ) {
		int strsize = snap.KeyBufferSize(i) + 1;
		char[] key_buffer = new char[strsize];
		snap.GetKey(i, key_buffer, strsize);
		PackVal val;
		cfg.GetArray(key_buffer, val, sizeof(val));
		switch( val.tag ) {
			case KeyValType_Value:
				val.data.Reset();
				/// do something with string value.
			case KeyValType_Section: {
				val.data.Reset();
				ConfigMap section = val.data.ReadCell();
				/// do something with section
			}
		}
	}
	delete snap;
```
