### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#18]
Putting this here for recording purposes, since I've already mentioned it twice before.

The plugin currently will not compile unless you add "modules/" to the path of every #include that references a file within that folder.

**Comment by assyrianic** [comment]
are you compiling on linux or windows?

**Comment by Starblaster64** [comment]
Windows 7, SM1.8

**Comment by assyrianic** [comment]
I could just do a "windows/linux" one but I guess i'll be safe and just put "modules/" on everything

**Comment by assyrianic** [comment]
alright, I applied it and it compiled fine so it HAS to be a bug on one of them but it should be fixed.
