### ISSUE TITLE
make OnBossBackstabbed event separate from OnBossTakeDamage event

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#19]
I believe for better clarity of modifying and controlling boss logic, should the backstab logic be an overall separate event from OnBossTakeDamage?

**Comment by Starblaster64** [comment]
I suppose it would make backstab related changes mildly easier to do. Would you separate the Market Garden code as well in that case?

**Comment by Starblaster64** [comment]
Then again, it might be better to keep all damage related stuff with the OTD events.

**Comment by assyrianic** [comment]
OTD events are already together, I'm just splitting up the branching code for the sake of easier modification.

**Comment by Starblaster64** [comment]
That wasn't quite what I meant, but in suppose there's no harm separating it.
