### ISSUE TITLE
RoundEnd bugging out

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#2]
occasionally and sometimes frequently, the RoundEnd code doesn't run. Problem with this is that the boss' queue points don't return to 0 and the person who was the boss when this occurs infinitely becomes the boss unless they reset their queue points manually.

**Comment by Starblaster64** [comment]
If the only issue is the queue points, couldn't you just fix it by resetting queue points WHEN a player becomes the Boss, rather than AFTER their round ends?

**Comment by assyrianic** [comment]
I believe this bug is fixed since 1.2.2 update
