### ISSUE TITLE
add support for medieval mode.

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#20]
Original VSH had a planned thing for medieval mode maps or servers but was never implemented.

The original mechanic was that medieval mode maps/servers would give players 3 lives since it was melee only.

**Comment by Starblaster64** [comment]
Should we add support for all (or most) game modes in that case? By which I mean converting all maps to Arena logic (or maybe get wacky and try objective based VSH).

**Comment by Starblaster64** [comment]
Potential conflict with #16

**Comment by assyrianic** [comment]
yes you're right, I'll have the respawn tickets system disabled in medieval mode maps/servers.
