### ISSUE TITLE
'Unusual' rounds

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#21]
Something I remember being a cool feature of the old OzFur VSH:Remake servers was that they had these randomly (though pretty uncommom) occuring 'Unusual' rounds. They would apply some unique round modifier for the current boss. Examples: http://vssaxtonhale.wikia.com/wiki/Unusual_Bosses
Obviously this would be an optional feature, with a CVAR. It could even just be a framework for round modifiers for server developers.

**Comment by assyrianic** [comment]
this can already be done with the current codebase. All that's necessary is to check if "it's an unusual round" and mark the boss that way, then set up the round as needed.
