### ISSUE TITLE
Add ConVar for sentries to die when engineer dies

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#22]
default cvar value will be false.

**Comment by Starblaster64** [comment]
You might as well expand it to have a third option while you're at it.

1. Destroy nothing
2. Destroy Sentry
3. Destroy all

Or you could even do a bitfield style thing where the CVAR controls exactly what buildings get destroyed, but maybe that's a little too extravagant.

**Comment by assyrianic** [comment]
added in 1.3.0 beta
