### ISSUE TITLE
Mediafire download link was taken down

### ISSUE THREAD

**Issue by metalbraix** [Starblaster64/Vs-Saxton-Hale-2#227]
due to a copyright strike

**Comment by HotoCocoaco** [comment]
Well I mean there's nothing we can do if the music has copyright claim.

**Comment by sopmub** [comment]
We'll probably either use a new hosting site and/or give CBS a placeholder if this proves to be an issue.

**Comment by kevyonan** [comment]
all files have now been added! Closing this _for now_
