### ISSUE TITLE
Modify Cap Points

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#23]
Would it be worth borrowing some Arena:Respawn code to make caps not an instant win on the first cap (maybe after 3 caps or something)?
Or is this the sort of thing that should just be left to server operators.
I'm asking because I just finished a working (albeit kind of spaghetti-coded) version of Chdata's unimplemented Cap Point idea that did effects on cap rather than win the round in my branch of VSH1.

**Comment by assyrianic** [comment]
slap cvars on everything ;)

**Comment by assyrianic** [comment]
also yes, we can add this in

**Comment by Starblaster64** [comment]
It's a bit of a mess with timers at the moment, it would probably be much cleaner using some GetEngineTime method. I'll post what spaghetti I do have anywY though.

**Comment by Starblaster64** [comment]
https://gist.github.com/Starblaster64/9dad240481ccdc5ed251a1d9a124dfa1

**Comment by assyrianic** [comment]
ok I added the code, however it's not stopping the cap from ending the round in one cap...
```c++
public Action PointCapture(Event event, const char[] name, bool dontBroadcast)
{
	if ( !bEnabled.BoolValue or gamemode.iRoundState != StateRunning or !cvarVSH2[MultiCapture].BoolValue )
		return Plugin_Continue;
	
	// int iCap = GetEventInt(event, "cp"); //Doesn't seem to give the correct origin vectors
	int iCapTeam = event.GetInt("team");
	gamemode.iCaptures++;
	
	if (gamemode.iCaptures >= 3 or (GetLivingPlayers(RED) == 1 and iCapTeam == RED))
	{
		ForceTeamWin(iCapTeam);
		return Plugin_Continue;
	}
	SetPawnTimer(_SetCapOwner, 0.1, iCapTeam);
	
	//int i = -1;
	switch (iCapTeam) {
		case BLU: {
			char sCappers[MAXPLAYERS+1];
			event.GetString("cappers", sCappers, MAXPLAYERS);
			BaseBoss boss = BaseBoss(sCappers[0]);
			if (boss) {
				//ManageOnBossCap(sCappers, iCapTeam);
			}
		}
		case RED: {
			char sCappers[MAXPLAYERS+1];
			event.GetString("cappers", sCappers, MAXPLAYERS);
			//ManageOnBossCap(sCappers, iCapTeam);
		}
	}
	return Plugin_Continue;
}
```

**Comment by Starblaster64** [comment]
Did you add the code I pasted at the very bottom? If the team_control_point_master isn't set to block both teams from winning, the round will end as usual.

**Comment by assyrianic** [comment]
success! got it working!
Now I'll add to the API a new event for when a cp is captured on while multicapture cvar is on.

**Comment by Starblaster64** [comment]
Sorry, I forgot to mention the code that changed the colour of the control point prop as well. Reopening this so I remember to commit it this weekend.
