### ISSUE TITLE
Migrate to Sourcemod 1.11

### ISSUE THREAD

**Issue by HotoCocoaco** [Starblaster64/Vs-Saxton-Hale-2#231]
[HotoCocoaco/Vs-Saxton-Hale-2/tree/sm-1.11](https://github.com/HotoCocoaco/Vs-Saxton-Hale-2/tree/sm-1.11)

Make some changes to make it able to be compiled in 1.11.

- ~~Use fixed-size array instead of dynamic-size array in [vsh2.inc#L1158](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/include/vsh2.inc#L1158) .~~ This is probably bad. Scalar assignment to array is deprecated in 1.11.
- Make `VSHGameMode` a independent instance instead of inside `VSH2Globals`.
- Return 0 to every int function that doens't return a value.
- Minor fixes.

However it's cannot be compiled in 1.10. :[
~~Not tested in-game. It should be ok because no big changes to the codes.~~
It's proved working in my own server.

**Comment by fxss-repository** [comment]
Not compiling on Windows 10 with 1.11 compiler.

//// vsh2.sp
// modules\base.sp(633) : error 017: undefined symbol "g_vshgm"

**Comment by HotoCocoaco** [comment]
> Not compiling on Windows 10 with 1.11 compiler.
> 
> //// vsh2.sp // modules\base.sp(633) : error 017: undefined symbol "g_vshgm"

You cannot compile 2.12 in Windows compiler either. Try linux.

**Comment by fxss-repository** [comment]
What is the difference between the Windows operating system compiler and Linux?
Are you using some kind of compiler of your own?

**Comment by HotoCocoaco** [comment]
> What is the difference between the Windows operating system compiler and Linux? Are you using some kind of compiler of your own?

The file system seems different when handling include sp files. I have tried to compile 2.12 on both Windows and Linux. And only Linux compiler works.

> // modules\base.sp(633) : error 017: undefined symbol "g_vshgm"

https://github.com/HotoCocoaco/Vs-Saxton-Hale-2/blob/sm-1.11/addons/sourcemod/scripting/modules/gamemode.sp#L640
It's defined here. And somehow Linux compiler will save that variable as a global var.

**Comment by HotoCocoaco** [comment]
> What is the difference between the Windows operating system compiler and Linux? Are you using some kind of compiler of your own?

Fix Windows build. Compiled with SourcePawn Compiler 1.11.0.6919 on Windows.
https://github.com/HotoCocoaco/Vs-Saxton-Hale-2/commit/4c55c9cfc96849efae7544e90d6911daab275a2e

**Comment by DatOpb** [comment]
We have fixed cross compile issues on Linux and Windows in the 2.13 update. It should be 1.11 compatible when 2.13 is released.

**Comment by HotoCocoaco** [comment]
Closed. https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/commit/7395bbbdfb4283d4353c72f73427b6778b963d1f
