### ISSUE TITLE
[REQ] Make cvar/option that makes the plugin only work on maps that start with 'vsh'

### ISSUE THREAD

**Issue by FaxMac** [Starblaster64/Vs-Saxton-Hale-2#233]
I am hosting a server that has a bunch of different modes and the issue is that the plugin runs in every map, I tried to configure so it only works on certain maps but i can't make it work.

If this gets implemented, I would greatly appreciate it

**Comment by FaxMac** [comment]
Also, to append an issue, putting vsh2_enabled 0 either in server.cfg or sourcemod.cfg wont turn off the plugin, the exec command works tho

**Comment by kevyonan** [comment]
you can already do this by editing the [`saxton_hale_maps.cfg` file](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/configs/saxton_hale/saxton_hale_maps.cfg) to just `vsh_` prefix.

It didn't work?

**Comment by FaxMac** [comment]
Ah, I installed this directly from Aliedmodders forum, I did not know that it was a feature

Thanks.
