### ISSUE TITLE
Spamming error log

### ISSUE THREAD

**Issue by TolikCorp** [Starblaster64/Vs-Saxton-Hale-2#237]
L 03/02/2023 - 19:43:53: [SM] Exception reported: Translation failed: invalid client index 1634558276 (arg 7)
L 03/02/2023 - 19:43:53: [SM] Blaming: vsh2.smx
L 03/02/2023 - 19:43:53: [SM] Call stack trace:
L 03/02/2023 - 19:43:53: [SM]   [0] Format
L 03/02/2023 - 19:43:53: [SM]   [1] Line 2226, modules/handler.sp::ManageFighterHUD
L 03/02/2023 - 19:43:53: [SM]   [2] Line 1979, modules/handler.sp::ManageFighterThink
L 03/02/2023 - 19:43:53: [SM]   [3] Line 846, vsh2.sp::Timer_PlayerThink

Info about server:

 SourceMod Version Information:
    SourceMod Version: 1.11.0.6931
    SourcePawn Engine: 1.11.0.6931, jit-x86 (build 1.11.0.6931)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Feb 12 2023 18:17:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/99a99484
    Build ID: 6931:99a99484
    http://www.sourcemod.net/
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1148
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Jun 26 2022 08:01:32
    Built from: https://github.com/alliedmodders/metamod-source/commit/4bdc218
    Build ID: 1148:4bdc218
    http://www.metamodsource.net/
Listing 6 plugins:
  [01] SourceMod (1.11.0.6931) by AlliedModders LLC
  [02] TF2Items (1.6.4) by Asherkin & AzuiSleet & Damizean
  [03] TF2 Tools (1.11.0.6931) by AlliedModders LLC
  [04] SDK Hooks (1.11.0.6931) by AlliedModders LLC
  [05] SDK Tools (1.11.0.6931) by AlliedModders LLC
  [06] SteamTools (0.10.0+54fdc51) by Asher "asherkin" Baker
[SM] Listing 29 plugins:
  01 "MapChooser" (1.11.0.6931) by AlliedModders LLC
  02 "Rock The Vote" (1.11.0.6931) by AlliedModders LLC
  03 "Basic Ban Commands" (1.11.0.6931) by AlliedModders LLC
  04 "Reserved Slots" (1.11.0.6931) by AlliedModders LLC
  05 "[Fork] High Ping Kicker" (1.1.4) by KorDen, (rewritten Nek.'a 2x2 | ggwp.site , by Grey83))
  06 "Player Commands" (1.11.0.6931) by AlliedModders LLC
  07 "Fun Commands X" (2.7) by Spazman0 and Arg!
  08 "Vs Saxton Hale 2 Mod" (2.12.0) by Nergal/assyrian, props to Flamin' Sarge, Chdata, Scags, & Buzzkillington
  09 "Admin Help" (1.11.0.6931) by AlliedModders LLC
  10 "Map Nominations" (1.11.0.6931) by AlliedModders LLC
  11 "Welcome Sound" (0.0.1) by R-Hehl
  12 "Basic Commands" (1.11.0.6931) by AlliedModders LLC
  13 "Fun Votes" (1.11.0.6931) by AlliedModders LLC
  14 "VSH2 Plague Doctor Subplugin" (1.0) by Nergal/Assyrian
  15 "RandomCycle" (1.11.0.6931) by AlliedModders LLC
  16 "Anti-Flood" (1.11.0.6931) by AlliedModders LLC
  17 "Admin File Reader" (1.11.0.6931) by AlliedModders LLC
  18 "Fun Commands" (1.11.0.6931) by AlliedModders LLC
  19 "Sound Commands" (1.11.0.6931) by AlliedModders LLC
  20 "[TF2] TF2Attributes" (1.7.2) by FlaminSarge
  21 "Basic Votes" (1.11.0.6931) by AlliedModders LLC
  22 "ChangeVars.smx"
  23 "Basic Comm Control" (1.11.0.6931) by AlliedModders LLC
  24 "Basic Info Triggers" (1.11.0.6931) by AlliedModders LLC
  25 "Client Preferences" (1.11.0.6931) by AlliedModders LLC
  26 "Admin Menu" (1.11.0.6931) by AlliedModders LLC
  27 "Nextmap" (1.11.0.6931) by AlliedModders LLC
  28 "Basic Chat" (1.11.0.6931) by AlliedModders LLC
  29 "[TF2] Double jump" (1.0) by Jughead
[SM] Displaying 12 extensions:
[01] Automatic Updater (1.11.0.6931): Updates SourceMod gamedata files
[02] Webternet (1.11.0.6931): Extension for interacting with URLs
[03] TF2Items (1.6.4): TF2 Item Modifier
[04] TF2 Tools (1.11.0.6931): TF2 extended functionality
[05] BinTools (1.11.0.6931): Low-level C/C++ Calling API
[06] SDK Hooks (1.11.0.6931): Source SDK Hooks
[07] SDK Tools (1.11.0.6931): Source SDK Tools
[08] Top Menus (1.11.0.6931): Creates sorted nested menus
[09] Regex (1.11.0.6931): Provides regex natives for plugins
[10] SteamTools (0.10.0+54fdc51): SteamWorks for SourceMod
[11] Client Preferences (1.11.0.6931): Saves client preference settings
[12] SQLite (1.11.0.6931): SQLite Driver

**Comment by assyrianic** [comment]
likely because of this:
https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/handler.sp#L2225-L2229

**Comment by kevyonan** [comment]
Likely because of this:

https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/7395bbbdfb4283d4353c72f73427b6778b963d1f/addons/sourcemod/scripting/modules/handler.sp#L2226

https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/7395bbbdfb4283d4353c72f73427b6778b963d1f/addons/sourcemod/scripting/modules/handler.sp#L2228

something tells me they should be:
`Format(HUDText, sizeof(HUDText), "%s\n%T", HUDText, "shield_active", i);`

@HotoCocoaco

**Comment by HotoCocoaco** [comment]
> Likely because of this:
> 
> https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/7395bbbdfb4283d4353c72f73427b6778b963d1f/addons/sourcemod/scripting/modules/handler.sp#L2226
> 
> https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/7395bbbdfb4283d4353c72f73427b6778b963d1f/addons/sourcemod/scripting/modules/handler.sp#L2228
> 
> something tells me they should be: `Format(HUDText, sizeof(HUDText), "%s\n%T", HUDText, "shield_active", i);`
> 
> @HotoCocoaco



Damn. I forgot to push the correct branch.
