### ISSUE TITLE
Name Change?

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#24]
I was thinking, instead of having the name as "Vs. Saxton Hale 2", it should be renamed to "Super VS. Saxton Hale" aka Super VSH or "Freak Fortress 1" ? lol.

Idea is to set a new name to differentiate it from the original VSH even though it sorta stems from it but the purpose is to emphasize that VSH2 is very different and built with a different purpose.

**Comment by Starblaster64** [comment]
Customizable versus mode plugin
CVSMP/CVMP/CVSM/CVM

Neo Vs. Saxton Hale
NVSH

Boss Battles Redux
BBR

Versus Anything
VSA

Vs the boss
VTB

VSH++


Honestly though, I think VSH2 fits ok. Maybe rebranding as VSH 2.0 might be good, since VSH1 never surpassed 1.x.
