### ISSUE TITLE
Switch to VSH1's method of precaching custom content

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#27]
I just realized VSH2 isn't using VSH1's PrepareModel/Material/Sound (and other such functions) stocks, which combine adding to the downloads table and precaching into one function.
While I'm addressing #26 I'll work this as well.

**Comment by assyrianic** [comment]
that's because the boss source files do that...

**Comment by Starblaster64** [comment]
I'm not quite sure I understand what you mean by that. The boss source files were not using the stocks present in VSH1, I just added them to the VSH2 stocks.inc then replaced all the precaching/addtodownloads stuff in each of the boss source files.
