### ISSUE TITLE
'Targe 2 hits requirement before breaking not working properly

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#31]
After simply being hit even once (with any shield equipped), the Targe 2-hits thing stops working until the plugin is reloaded (aka map change).

**Comment by assyrianic** [comment]
not a bug but oversight. iHits property doesn't reset when round is over.
whoopsy :/

**Comment by Starblaster64** [comment]
Fixed by 1906a81 and 13aa610.
