### ISSUE TITLE
Add Native (optional) Goomba Stomp Support

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#32]
Would be another event like the current ManageOnBossDealDamage etc.

**Comment by assyrianic** [comment]
not quite sure this is entirely necessary considering many vsh servers wouldn't be caught dead without goomba since it helps equalize against the boss.

One idea is maybe implement the goomba natively? Add a cvar for it too.

**Comment by assyrianic** [comment]
lel didn't understand it. I say jes

**Comment by Starblaster64** [comment]
Should I put the OnStomp event in `events.inc` or `vsh2.sp` next to OnTakeDamage?

**Comment by assyrianic** [comment]
well if it acts similar to a source engine event, probably best to put it in Events; after that, split it into two event functions as OnBossStomped and OnPlayerStomped.

Or we can kill two birds with one stone by directly placing it in handler.sp and have the function parameters coerce to the BaseBoss methodmap.

**Comment by Starblaster64** [comment]
The format of it (`public Action OnStomp(int attacker, int victim, float& damageMultiplier, float& damageAdd, float& JumpPower)`) is more akin to the OnTakeDamage hooks.

**Comment by assyrianic** [comment]
for handler, easy case.

maybe do something like
```c++
BaseBoss boss = BaseBoss(client);
if (boss.bIsBoss) {
   switch (boss.iType) {
        case -1: {} // Ignore if not boss at all.
        case etc.
   }
   return ...;
}
boss = BaseBoss(attacker);
if ( boss.bIsBoss ) {
   switch (boss.iType) {
        case -1: {} // Ignore if not boss at all.
        case etc.
   }
   return ...;
}
```

**Comment by assyrianic** [comment]
has this been done in already? I need to revive-bump the VSH2 thread back into the 1st page lol

**Comment by Starblaster64** [comment]
Sorry! I've been kind of busy these past few weekends (physically my only time to work on projects currently), and the ones where I wasn't I didn't really have the motivation to be productive. I also have something I'm supposed to finish up this weekend (possible I might have it done soon enough to work on other stuff). If you really need the bump now, you'll have to do it without goomba stomp stuff, or put it in yourself if you have the time.

**Comment by assyrianic** [comment]
alrighty, is the current source compilable?

**Comment by Starblaster64** [comment]
Yes (Travis build log is positive), just hold off for a few hours, I want to double check if I have anything I didn't push on my local repo when I get home this evening (SG Time).

**Comment by Starblaster64** [comment]
@assyrianic OK!, Set up the release: https://github.com/Starblaster64/Vs-Saxton-Hale-2/releases/tag/1.3.6
It's 1.3.6 instead of 1.4.0 because there were no really significant changes (e.g Goomba stomp integration).

**Comment by assyrianic** [comment]
alliedmodders post updated B)

**Comment by assyrianic** [comment]
any part of the API changed to where the Wiki needs updating?

**Comment by Starblaster64** [comment]
Right then, finally got around to working on this, just gonna clean it up then I'll push it to a separate branch before merging.
The API will (maybe) need a pretty small update with regards on how to add custom Goomba Stomp behaviour to new/existing Bosses once I push it. It's pretty much identical to how you'd do it with OnTakeDamage anyway.

**Comment by assyrianic** [comment]
excellent, update the API ref as u need!
