### ISSUE TITLE
Change Demoman Shield Crits to scale by Charge meter

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#33]
Instead of full on 100% crits (which in most cases, is extremely OP for the Demoman), how about having it scale up from no-crits, to mini-crits, and finally regular crits proportionally to the charge meter?

0-35% would be no buff, 35-85% would be minicrits, 85+% would be crits (percentages subject to change under testing, of course),  and a broken shield would be crits/minicrits (since they're vulnerable without the shield escape the crits aren't as OP in that case).

**EDIT:** Add optional CVAR as well, perhaps.

**Comment by assyrianic** [comment]
shur
