### ISSUE TITLE
Update Compatability with Scream Fortress VIII (Preemptive)

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#34]
Just preemptively making this issue to use as a checklist for any problems that arise from this year's Halloween update (scheduled to go live tomorrow).

- [ ] N/A

**Comment by assyrianic** [comment]
any bugs?

**Comment by Starblaster64** [comment]
Doesn't look like it, I'll close the issue for now and reopen it if I find any.
