### ISSUE TITLE
crazy idea - using an internal interpreter to make sub-sub-plugins for the mod?

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#35]
basically when VSH2 is running, it'll control boss code through an interpreter to a folder and it will run code according to the boss it is for.

Think the idea of QuakeC for the Quake engine. This idea is basically an alternative to give not only coding power to newbies and server operators but it'll match against FF2's config system by having an easy scripting language.

I'm thinking it'll be a very simple and easy to learn scripting sub-language too.

**Comment by assyrianic** [comment]
im think it'd be a very very simple c-like language.

**Comment by Starblaster64** [comment]
Sounds very ambitious.
Also, just so you know the Pending Review label is meant for Pull Requests only, and only for when they're about to be merged (like a final inspection) p:

**Comment by assyrianic** [comment]
basically I'm thinking, the interpreter will work side by side with the whole "boss event handling and source file compilation" system. IF that works of course.

**Comment by assyrianic** [comment]
I'm starting work on the interpreter right now. Firstly I'm building it as a normal sourcepawn plugin. Perhaps I'll add natives to it so it can be embedded into any sourcepawn plugin and run.

The only problem is what kind of language to make it lol. Do you know a very easy language to learn that perhaps I can emulate? I was thinking either Lua or Python but this needs to be even simpler for server operators who likely do not know how to code at all.

**Comment by Starblaster64** [comment]
I'm not sure if it's really worth it. I mean, if we're talking about server operators who don't know how to code at all, why would they bother with any form of coding, however simple it might be? Unless you could make it as simple as _config files_, I don't see how you're going to get the majority of FF2-esque server operators to try it in the first place. And in addition, how are you going to keep the extensiveness of VSH at the same time for more advanced programmers?

I would assume the kind of person who would use this system already knows a bit about coding (or at the very least has an interest in it and wants to improve), in which case why not just learn full on SourcePawn? It just seems like you'd have to make the sub-language ridiculously simple, to the point where it's almost config level. Which, you know, defeats the point of VSH2.

That being said, it could prove to be an interesting idea on its own, as you said with the natives and such.

To answer your original question; Ruby is apparently a very simple language that also boasts readability for non-coders. However, I haven't actually used it before so I don't know personally.
If it were possible to emulate something like a SourcePawn-Lite, then I'd probably suggest that instead.

**Comment by assyrianic** [comment]
what you mean a sourcepawn lite?

**Comment by Starblaster64** [comment]
Probably wouldn't even work, I was just imagining SourcePawn, but really simple.

**Comment by assyrianic** [comment]
nvm I've scrapped this idea. perhaps VSH2 is powerful as is. No need to bloat it with extra stuff.
