### ISSUE TITLE
Stop engineer from announcing every time he builds

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#36]
minor issue is that every time an engineer builds, he (idiotically) yells about what he's building and gives away his position. This small code hopefully should silence so that engineers don't screw themselves over.

```c++
#include <sourcemod>
#include <sdktools>

char samples[][] = {
	"engineer_autobuildingsentry",
	"engineer_autobuildingteleporter",
	"engineer_autobuildingdispenser",
	"engineer_sentrymoving",
	"engineer_sentrypacking",
	"engineer_sentryplanting"
};

public Plugin myinfo = {
	name = "Block Engineer Announcements",
	author = "Powerlord",
	description = "Shh, I'm buildin' a sentry.",
	version = "1.1",
	url = "https://forums.alliedmods.net/showthread.php?t=191220"
}

public OnPluginStart()
{
	AddNormalSoundHook(EngySoundHook);
}

public Action EngySoundHook(int clients[64], int& numClients, char sample[PLATFORM_MAX_PATH], int& entity, int& channel, float& volume, int& level, int& pitch, int& flags)
{
	int size = sizeof(samples);
	for (int i=0; i<size; i++) {
		if (StrContains(sample, samples[i], false) > -1)
			return Plugin_Handled;
	}
	return Plugin_Continue;
}
```

**Comment by Starblaster64** [comment]
I have literally never had this be an issue in VSH.
Also, the building construction sound or you know, the loud wrench-on-metal sounds would give you away regardless.

**Comment by assyrianic** [comment]
yes but they don't resonate as loud as the engineer voiceclips.

**Comment by Starblaster64** [comment]
But the wrench sound will be constant if the Engineer wants his buildings up faster (and even afterwards while upgrading), as opposed to a single voice clip that lasts less than a couple of seconds. And honestly I'd be surprised if most people could even pick out any of these sounds amongst the usual gunfire and explosion noises that accompany the VSH-type gamemode. Even if they could, their position would probably be masked by all the other noise going on. If someone takes the time to consistently recognize and triangulate all of the Engineer voice lines in any noise level, then they've earned that advantage in my opinion.

Also, this seems like the sort of thing that should be kept to external plugins to handle. It's not really integral to the plugin or the general game mode. VSH was never *really* about stealth, you'll be found sooner or later if the boss has half a brain.
