### ISSUE TITLE
Bosses suiciding as soon as the round starts

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#37]
I think the VSH1 code to block boss suiciding and joining red team should work in this case.

I was going to do the code myself but I'm tied as I need to remake my server since my community owner wiped it >_>

**Comment by Starblaster64** [comment]
Sounds good, I'll toss in a CVAR to control how long until the Boss is allowed to suicide as well.
Good luck with your server, sounds rough.

**Comment by assyrianic** [comment]
fixed and I did not put in a cvar.
