### ISSUE TITLE
Implement some features from BBG's custom FF2 fork?

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#39]
With the recent closing of BBG's TF2 servers, Shadow93/Koishi has decided to release the source code for their custom FF2 fork to the public.
No harm in browsing through it for any nice features to add to VSH2.

**Comment by assyrianic** [comment]
visible wep models is very trivial at the moment unless you mean boss stuff but still.
>Noticed low priority. Oh sure why not!

**Comment by Starblaster64** [comment]
@assyrianic Yea I know, I was going to put more in the list but that was the first thing that came to mind when I opened the issue and I haven't taken a good look at the source yet.
Also, looks like the Big Bang website has officially shut down, so the download link is no longer accessible. I managed to download a copy before it went down though so I'll take a look later (let me know if you want a copy).
