### ISSUE TITLE
replace methodmap global vars with StringMap equivalent

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#40]
This is an enhance that I'm planning myself to do, basically gonna replace the backing variables for the methodmaps with StringMaps (aka dictionaries) for the sake of organization and faster code updating.

The benefit to this is that, since dictionaries have O(1) time for all necessary operations in this case, we won't lose much needed speed performance.

I'm putting this as an issue so I can remind myself to do it.

**Comment by Starblaster64** [comment]
I still haven't quite worked out how to work with MethodMaps, so StringMaps will probably confuse me even more.
But if it's gonna make updating code faster then I'm all for it.

**Comment by assyrianic** [comment]
basically, if you've used Python, StringMaps are pretty much dictionaries or as python calls them: "dicts"

another name for them as "associative arrays" where key and a value that pertains to that key are connected to a certain index. They're a very old data structure, thought up in the 1950s
