### ISSUE TITLE
Fix TF2Attributes not being an Optional dependency

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#41]
So it IS optional on compile, but it is not optional to NOT run the TF2Attbs plugin if VSH2 was compiled with it.

To fix it, we just need to make a copy paste of the SteamTools enabled bool for TF2Attbs, then apply it in the same way VSH1 has done.

**Comment by Starblaster64** [comment]
Alternatively, make it a *required* dependency both on compile and while running.

**Comment by assyrianic** [comment]
I was thinking it should be optional considering TF2Attribs has a tendency to break sometimes and I'd rather not have server operators worry wtf is going on with their servers because a plugin spazzed out due a single breakage.

**Comment by assyrianic** [comment]
as for the boolean, sure!

**Comment by assyrianic** [comment]
I added a property to the gamemode methodmap called bTF2Attribs and it's already in good use. Test out to make sure it's 100% workin'. I tested it out on my personal server and it seems to be working fine.

**Comment by assyrianic** [comment]
this one is very much fixed I believe!
