### ISSUE TITLE
Error: Client is not in game (ManageDisconnect)

### ISSUE THREAD

**Issue by CookiesIO** [Starblaster64/Vs-Saxton-Hale-2#42]
Sometimes the following shows up in our error logs
```
L 12/10/2016 - 11:56:15: [SM] Exception reported: Client 1 is not in game
L 12/10/2016 - 11:56:15: [SM] Blaming: customPlugins/vsh2.smx
L 12/10/2016 - 11:56:15: [SM] Call stack trace:
L 12/10/2016 - 11:56:15: [SM]   [0] IsPlayerAlive
L 12/10/2016 - 11:56:15: [SM]   [1] Line 90, modules/handler.sp::ManageDisconnect
L 12/10/2016 - 11:56:15: [SM]   [2] Line 438, vsh2.sp::OnClientDisconnect
```

A possible fix is to add IsClientInGame prior to IsPlayerAlive, or around depending on what should be run only when the client is In Game, [in ManageDisconnect in handler.sp](https://github.com/Starblaster64/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/handler.sp#L90). A client disconnecting does not equate to them being in-game, it only means they were at least connected.

**Comment by assyrianic** [comment]
ayyy cookies, I made a small attempt at a fix, hopefully it should resolve some of the issues.
