### ISSUE TITLE
add updater support

### ISSUE THREAD

**Issue by kevyonan** [Starblaster64/Vs-Saxton-Hale-2#58]
to help facilitate faster updating, I think the plugin really needs updater.

**Comment by Starblaster64** [comment]
Never set up a plugin with updater before. Don't we need to like host the files somewhere? Or can we substitute that with GitHub.

**Comment by kevyonan** [comment]
it's easy actually. We need to setup a place where servers can directly download the newer version plugin which can be right here in github. look at my mechanized mercs repo -> https://github.com/assyrianic/-TF2-Mechanized-Mercs

As you can see, the new version compiled smx is in the plugins folder. Updater plugin looks at the updater.txt file to see if there's an update and then prompts the server to download and place the new plugin.

Perhaps you can setup travis to place the new, successfully compiled smx into the github folder here?
