### ISSUE TITLE
Misc Changes

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#59]
A to-do list with several balance changes and bug fixes I've compiled over the past few weeks.

TODO:
- [ ] Write out TODO list (mostly just lots of minor stuff, also an experimental Eureka Effect change)
- [ ] Experimental Eureka Effect rework.
- [ ] Several changes found [here.](https://github.com/Starblaster64/Versus-Saxton-Hale/releases/tag/1.55g)

**Comment by kevyonan** [comment]
adding this link here as a backdrop for more weapons changes to make:
https://www.skial.com/threads/vsh-ff2-weapon-balancing.82287/

**Comment by kevyonan** [comment]
think of better changes for these weapons:
- [x] Razorback
- [x] Darwins Danger Shield
- [x] Axtinguisher
- [x] Short Circuit
- [ ] Homewrecker
- [ ] Righteous Bison
- [ ] Persian Persuader
- [ ] Fists of Steel
- [ ] Neon Annihilator
