### ISSUE TITLE
add more VSH2/Gameplay oriented commands.

### ISSUE THREAD

**Issue by kevyonan** [Starblaster64/Vs-Saxton-Hale-2#63]

**Comment by Starblaster64** [comment]
Any examples?
I'd like to suggest a `sm_vsh2_reload` command though, like VSH1's `sm_hale_reload`.

**Comment by kevyonan** [comment]
sure, what does 'sm_hale_reload' do ?

**Comment by Starblaster64** [comment]
Sets the plugin to reload itself during the next round end (or right away if it's already the round end).
