### ISSUE TITLE
Convert sniperrifle index switch statement to a classname check instead

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#71]
More future-proof/convenient than manually adding new weapon indexes all the time.

I already did this in a pull request for VSH1: https://github.com/Chdata/Versus-Saxton-Hale/pull/20/files
Simple enough to just modify it for VSH2.

**Comment by kevyonan** [comment]
I approve. I'd help test it out but my gaming computer is busted. If you need help with anything, do not hesitate to message me here or on discord.

**Comment by Starblaster64** [comment]
~~My computer just stopped working too this evening. Beep code sounds like a memory error, but I won't be able to diagnose it until Friday.~~ 
~~Nevermind, it decided to fix itself.~~
Broken again, rip.

**Comment by kevyonan** [comment]
issue has been resolved!
