### ISSUE TITLE
Melee Weapons Have no crits

### ISSUE THREAD

**Issue by Derphammer** [Starblaster64/Vs-Saxton-Hale-2#76]
As the title says Melee weapons have lost Crits along with scout pistols.

**Comment by Derphammer** [comment]
Also commands like haleselect do not work 

on a side note is there a way to increase hales hp formula as with 32 people on the server he tends to die very very fast.  i have noticed That With the class changes and the buffs they have gotten like the spy and medic, they tend to kill him very fast and are really hard to kill.

**Comment by kevyonan** [comment]
hello Derphammer, what version of SM and metamod are you using?

**Comment by Derphammer** [comment]
Version 1.8.0.6035

**Comment by kevyonan** [comment]
@Derphammer that's outdated, use 1.9 SM

**Comment by Derphammer** [comment]
ok will update it and try it out in a sec will let you know if anything changes with crits and commands

**Comment by kevyonan** [comment]
ok!

**Comment by Derphammer** [comment]
ok after testing you only get melee crits when you are one of the last two alive but besides that they still do not have crits after updating sm

**Comment by kevyonan** [comment]
hmm
I'll look into this.

**Comment by kevyonan** [comment]
i've made a large update for the mod, try now and tell me if the melee weapons still don't have crits.

**Comment by Derphammer** [comment]
Will do thanks for the quick work man. everyone is loving the vsh2 since we replaced vsh.

**Comment by kevyonan** [comment]
no problem

**Comment by kevyonan** [comment]
is the issue still around?

**Comment by kevyonan** [comment]
@Derphammer no confirmation whether this is resolved or not?

**Comment by Derphammer** [comment]
Melee crits are now working, thanks for the quick and fast fix.
