### ISSUE TITLE
Finish FF2 Compatibility Layer for VSH2

### ISSUE THREAD

**Issue by kevyonan** [Starblaster64/Vs-Saxton-Hale-2#77]
all in the title.
Allow for seamless transition to VSH2 for FF2 users by having VSH2 create a compatibility layer.

**Comment by kevyonan** [comment]
one possible strategy for this is by having the FF2 API implementation call into VSH2 code.

**Comment by kevyonan** [comment]
This can also be applied as a VSH2 addon plugin as well but would require FF2 being removed.

**Comment by TheBluekr** [comment]
> one possible strategy for this is by having the FF2 API implementation call into VSH2 code.

Parse the configs, call the respective global forwards?
Making currently an attempt at it. I'll report back once I've made some more progress.

**Comment by kevyonan** [comment]
Adding this as link https://github.com/50DKP/FF2-Official/blob/experimental/addons/sourcemod/scripting/include/freak_fortress_2.inc

@TheBluekr how goes progress?

**Comment by TheBluekr** [comment]
Not making as much as progress as I would like.

**Comment by Batfoxkid** [comment]
Might want to use the [stable branch](https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/scripting/include/freak_fortress_2.inc "FF2-Official/freak_fortress_2.inc at stable   50DKP/FF2-Official") or [my version](https://github.com/Batfoxkid/FreakFortressBat/blob/development/addons/sourcemod/scripting/include/freak_fortress_2.inc "FreakFortressBat/freak_fortress_2.inc at development   Batfoxkid/FreakFortressBat"). The experimental branch is the forgotten FF2 2.0.

**Comment by TheBluekr** [comment]
Latest additions might really help.
I had to use some hacky way to customize max health.

**Comment by kevyonan** [comment]
@TheBluekr no worries, I've already made a prototype of the FF2 compatibility layer, I'll push it at a later date. I'm working with BatfoxKid in getting it functional while mitigating errors as much as possible.

**Comment by TheBluekr** [comment]
Neat, any place I can contact you to talk about it?

**Comment by kevyonan** [comment]
@TheBluekr If you have discord, the link to BatFoxKid's discord for FF2 & VSH https://discord.gg/j6NDdZ2

**Comment by kevyonan** [comment]
saving this here: https://github.com/Batfoxkid/FreakFortressBat/wiki/Example-Boss-Config

**Comment by kevyonan** [comment]
By BatFoxKid:

- [ ] Starting up subplugins in freaks/ folder
- [ ] Calling FF2_OnAbility for rages/passives in the config

For Subplugins:
- [ ] Loads once the first non-arena round begins.
- [ ] Unloads when the plugin is disabled (eg. sm plugins unload, server became empty, map just ended).
- [ ] Also subplugins file type is renamed to .ff2 to prevent them from loading automatically.

**Comment by kevyonan** [comment]
Leaving this here (FF2_OnAbility callback): https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/scripting/freak_fortress_2.sp#L4831-L4855

**Comment by kevyonan** [comment]
Example config to work with: https://github.com/50DKP/FF2-Official/blob/stable/addons/sourcemod/configs/freak_fortress_2/brutal_sniper_hale.cfg

**Comment by kevyonan** [comment]
Another side note: Find a way to register Character configs as bosses within VSH2 so they can be assigned a runtime ID.

**Comment by JassJam** [comment]
instead of loading every FF2 subplugin all at once, how about load a chunk of subplugins that's going to be used during spawn and unloading at round end, that might help with finding a bad plugin and/or performance

**Comment by kevyonan** [comment]
> instead of loading every FF2 subplugin all at once, how about load a chunk of subplugins that's going to be used during spawn and unloading at round end, that might help with finding a bad plugin and/or performance

this might be necessary if we're using global forwards. Perhaps we should have a max ability subplugin limit of 16 loaded at once?

perhaps a manager that uses a fixed size array + `StringMap` ?
```c++
enum { FF2_MAX_SUBPLUGINS = 16 };
enum struct FF2SubPlugins {
    Handle subplugin[FF2_MAX_SUBPLUGINS];
    StringMap names; /// map[string]int -> int is index into the array.
}
```

**Comment by JassJam** [comment]
i was thinking of a `StringMap` that holds handles to the subplugins and `StringMap.Size` should be less than `FF2_MAX_SUBPLUGINS`, but yet again caching them is kinda of risky because they will get invalidated when a subplugin reloads itself. unless there is some workaround like maybe creating console command that both reload the plugin and refresh the cache?

**Comment by kevyonan** [comment]
> i was thinking of a `StringMap` that holds handles to the subplugins and `StringMap.Size` should be less than `FF2_MAX_SUBPLUGINS`, but yet again caching them is kinda of risky because they will get invalidated when a subplugin reloads itself. unless there is some workaround like maybe creating console command that both reload the plugin and refresh the cache?

Boss Module's manager has some code that deals with reloaded plugins in [RegisterBoss](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/vsh2.sp#L1129-L1145). Essentially if we have a plugin name match but the plugin Handles are different, we can safely assume that plugin was likely reloaded. Otherwise if there was no name match, we can assume it's a new plugin being loaded for the first time.

**Comment by kevyonan** [comment]
@01Pollux With the FF2 compatibility engine as it is now, is it possible to have both VSH2 Boss modules alongside FF2 bosses? Can VSH2 switch between them at any time a boss is selected?

**Comment by JassJam** [comment]
Yes @assyrianic any base/extra VSH2 modules will work with or without FF2 interface. 
FF2 will also unloads its subplugins during main/VSH2 unload. Tho i should add a tiny guide to help out people who wants to make/update config/subplugin since there are improvements in both sides.

**Comment by kevyonan** [comment]
> Yes @assyrianic any base/extra VSH2 modules will work with or without FF2 interface.
> FF2 will also unloads its subplugins during main/VSH2 unload. Tho i should add a tiny guide to help out people who wants to make/update config/subplugin since there are improvements in both sides.

So would you say this issue can finally be closed?

**Comment by JassJam** [comment]
Feel free to do so, anything beyond this point can be considered as addition/minor fix or improvements to FF2
