### ISSUE TITLE
Client index 0 is invalid [vsh2.sp]

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#8]
L 09/04/2016 - 11:38:32: [SM] Exception reported: Client index 0 is invalid
L 09/04/2016 - 11:38:32: [SM] Blaming: vsh2.smx()
L 09/04/2016 - 11:38:32: [SM] Call stack trace:
L 09/04/2016 - 11:38:32: [SM]   [0] GetClientUserId
L 09/04/2016 - 11:38:32: [SM]   [1] Line 67, modules/base.sp::BaseFighter.BaseFighter()
L 09/04/2016 - 11:38:32: [SM]   [2] Line 557, modules/base.sp::BaseBoss.BaseBoss()
L 09/04/2016 - 11:38:32: [SM]   [3] Line 624, C:\hlserver\tf\addons\sourcemod\scripting\vsh2.sp::OnTakeDamage()

**Comment by assyrianic** [comment]
patched in next updating :+1:

**Comment by assyrianic** [comment]
fixed ^^
