### ISSUE TITLE
Native "Steam_SetGameDescription" was not found

### ISSUE THREAD

**Issue by fearts** [Starblaster64/Vs-Saxton-Hale-2#82]
L 10/06/2018 - 16:57:26: [SM] Unable to load plugin "vsh2.smx": Native "Steam_SetGameDescription" was not found

^This error stops the plugin from loading if you don't have SteamTools installed. In the coding it says SteamTools is optional but it still causes this errors.

As well, SteamTools is glitchy and broken since I believe the Inferno update. If you are going to change game description you should be using SteamWorks. 

Can you please either change this to SteamWorks or prevent this error from stopping the mod from loading if SteamTools isn't installed? 

Thank you.

**Comment by kevyonan** [comment]
i’ll have a look at this bug Fearts.

**Comment by kevyonan** [comment]
are you still getting this error?

**Comment by fearts** [comment]
I haven't checked because I edited the code myself to fix this problem. But I'm pretty sure it would still happen if nothing has been changed.

**Comment by fearts** [comment]
I just tested the newest version of VSH and I didn't get this issue. So seems to be fixed now.
