### ISSUE TITLE
!setboss menu broken after update

### ISSUE THREAD

**Issue by fearts** [Starblaster64/Vs-Saxton-Hale-2#85]
Not really sure when this started by I noticed it after the last TF2 update.

I loaded the base version of this plugin without plague doctor coding to my server. If you do !setboss and select any boss it doesn't pick the boss you selected and seems like it just chooses random always.

**Comment by fearts** [comment]
Also got this error in my logs but I'm not sure if it's related:

L 10/20/2018 - 15:26:15: [SM] Exception reported: Invalid Handle 0 (error 4)
L 10/20/2018 - 15:26:15: [SM] Blaming: vsh2.smx
L 10/20/2018 - 15:26:15: [SM] Call stack trace:
L 10/20/2018 - 15:26:15: [SM]   [0] StringMap.GetValue
L 10/20/2018 - 15:26:15: [SM]   [1] Line 737, modules/base.sp::BaseBoss.bIsBoss.get
L 10/20/2018 - 15:26:15: [SM]   [2] Line 69, modules/handler.sp::ManageDisconnect
L 10/20/2018 - 15:26:15: [SM]   [3] Line 568, vsh2.sp::OnClientDisconnect

**Comment by kevyonan** [comment]
unfortunately, I have no computer that can access TF2 so I can't really test anything :(
