### ISSUE TITLE
Plague Doctor

### ISSUE THREAD

**Issue by Derphammer** [Starblaster64/Vs-Saxton-Hale-2#86]
We are running into a issue with the plague doctors hitbox being super broken. 

what happens is when the plague doctor spawns in everyone goes to spy as when you are a spy fighting the plague doctor, you become god.  the spy can get a back stab on him no matter what direction he is facing. to test this out i went up the the plague doctor who was facing me and stabbed his foot which gave me a back stab hit. 

not really sure why no matter where u stab him its always a back stab but do you know of a fix or a way to get past this. 

i am using the current verson of sm and meta 

i am also using the most updated ver of the plugin.

**Comment by kevyonan** [comment]
strange bug, no lag issues?

**Comment by Derphammer** [comment]
correct no lag issue at all. not really sure whats going on here. 

if by chance you want to see the bug live i can give you my server ip.

**Comment by kevyonan** [comment]
that's the problem, I don't have a usable computer to even load up TF2 unfortunately :cry:  @Scags any idea on this?

**Comment by Scags** [comment]
[This line](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/vsh2boss_plaguedoctor.sp#L391) probably. It might be some weird thing comparing the property with a float value in the latter logical evaluation. I think maybe retrieving an int property as a float may cause it to flip out. I would test but am busy at the moment. 
Come to think about it, is it even necessary? It's actual purposeful occurrence would be with a facestab when a boss' health is < 120.

Edit:
Looking back at VSH1, it's just a straight TF_CUSTOM_BACKSTAB check.

**Comment by Derphammer** [comment]
not really sure on this i guess you are saying if the boss'es hp is higher then 120 you can get face stabs but the problem is no matter where you stab its always registered as a backstab and hits him for like 1.5k to 2k dmg. plague doctor has to get like 5 kills then hide and hope his scouts can build his army because even 1 spy vs him = no chance of the boss killing that spy as the spy will always get the 400 hp back. then if you get a spy that is actually good that spy will always have around 12k dmg or more vs him.

**Comment by kevyonan** [comment]
it's ALWAYS registering as a backstab? Even if the boss is completely still and you're looking at him straight in the face?
:open_mouth:

**Comment by Derphammer** [comment]
correct thats the issue we are having.

**Comment by kevyonan** [comment]
@Derphammer the issue has been resolved :)
