### ISSUE TITLE
Vagineer not getting Uber on 1st rage

### ISSUE THREAD

**Issue by fearts** [Starblaster64/Vs-Saxton-Hale-2#87]
I had reports from my players that Vagineer doesn't get uber on the first rage of a round but does after the first rage.

**Comment by kevyonan** [comment]
any formal tests on this?

**Comment by fearts** [comment]
Sorry I should have updated this. I did some testing and couldn't recreate it. Restarting the server seemed to fix it. If it continues to happen I will update.
