### ISSUE TITLE
Lastman Timer not ending round.

### ISSUE THREAD

**Issue by fearts** [Starblaster64/Vs-Saxton-Hale-2#88]
vsh2_health_percentage_last_guy "0"

vsh2_lastplayer_time "180"

When there is one player left a live it starts a count down but when it reaches 0 nothing happens.

**Comment by kevyonan** [comment]
I still don't have a computer to implement fixes :(

**Comment by kevyonan** [comment]
alright, someone was able to help me locate the bug, I patched it.
Build the developer version of vsh2 and check back with me.

**Comment by fearts** [comment]
I added the two extra lines into the code and it doesn't seem to have changed anything.

**Comment by kevyonan** [comment]
and the cvar `vsh2_health_percentage_last_guy` is set to `0` right?

**Comment by fearts** [comment]
Yes.

"vsh2_health_percentage_last_guy" = "0" ( def. "51" ) min. 0.000000 max. 255.000000

**Comment by kevyonan** [comment]
alright, fearts, check it out now.

**Comment by fearts** [comment]
Yea it works I had Mitch find the error for me.
