### ISSUE TITLE
Client-sided themes

### ISSUE THREAD

**Issue by Scags** [Starblaster64/Vs-Saxton-Hale-2#95]
Fairly straightforward; rather than using a global `gamemode.flMusicTime`, shift over to `BaseBoss.flMusicTime` and have the music function fire for each client.

Could also add client-sided volume control cookies too 😁

Edit:
This would also extend BackgroundSong to be a multidimensional array for each client, rather than the single song.

**Comment by kevyonan** [comment]
I'm still not 100% sure of this idea for the main repo.

**Comment by Scags** [comment]
Fair, it would be cool if there was a way to play sound files at a certain point in the file, though.

**Comment by kevyonan** [comment]
how about a compromise where I add a cvar that accomplishes this? The cvar will decide whether each individual client will have their own music timing or use a global song and time.

**Comment by kevyonan** [comment]
Implemented but cannot test without other players. @Scags
