### ISSUE TITLE
Enhance voicelines

### ISSUE THREAD

**Issue by Scags** [Starblaster64/Vs-Saxton-Hale-2#96]
Voicelines as they are now, aren't oriented to be heard from far distances and can overlap. It's a bit odd to hear the easter bunny grumble 3 different voicelines at the same time. And also, it's a bit annoying to wind up dead after realizing a boss superjumped and you didn't hear it.

VSH1 utilized the `speakerentity` param along with using different sound channels and stacked them with each sound bite so that they were hearable from across the map. With some exceptions, super jumps and rages I think had some differences in the item channel.

Lastly, it's rare, but sometimes sounds play when they shouldn't. The most common case was a superjump sound playing when Hale killed someone. I'm assuming this has to do with the global `snd` char which'll get tossed around and might keep some stuff it shouldn't. Should probably just remove it.

If you're down, I can tackle this and might as well add an option to disable voicelines too.

**Comment by kevyonan** [comment]
sure, not sure about the very last part to disable voicelines though, it's part of the immersion.
